// AUTOGENERATED with quazal-tools

#![allow(clippy::enum_variant_names, clippy::upper_case_acronyms)]
#[derive(ToStream, FromStream)]
pub struct UbiAuthenticationLoginCustomData {
    pub data: quazal::rmc::types::Data,
    pub user_name: String,
    pub online_key: String,
    pub password: String,
}
// Debug by hand (not derived): a password is never written to a log.
impl std::fmt::Debug for UbiAuthenticationLoginCustomData {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("UbiAuthenticationLoginCustomData")
            .field("data", &self.data)
            .field("user_name", &self.user_name)
            .field("online_key", &"<hidden>")
            .field("password", &"<hidden>")
            .finish()
    }
}
