// AUTOGENERATED with quazal-tools

#![allow(clippy::enum_variant_names, clippy::upper_case_acronyms)]
#[derive(Debug, ToStream, FromStream)]
pub struct ExternalAccount {
    pub account_type: u32,
    pub id: String,
    pub username: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct UbiAccountStatus {
    pub basic_status: u32,
    pub missing_required_informations: bool,
    pub recovering_password: bool,
    pub pending_deactivation: bool,
}
#[derive(ToStream, FromStream)]
pub struct UbiAccount {
    pub ubi_account_id: String,
    pub username: String,
    pub password: String,
    pub status: UbiAccountStatus,
    pub email: String,
    pub date_of_birth: quazal::rmc::types::DateTime,
    pub gender: u32,
    pub country_code: String,
    pub opt_in: bool,
    pub third_party_opt_in: bool,
    pub first_name: String,
    pub last_name: String,
    pub preferred_language: String,
    pub external_accounts: Vec<ExternalAccount>,
}
// Debug by hand (not derived): a password is never written to a log.
impl std::fmt::Debug for UbiAccount {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("UbiAccount")
            .field("ubi_account_id", &self.ubi_account_id)
            .field("username", &self.username)
            .field("password", &"<hidden>")
            .field("status", &self.status)
            .field("email", &self.email)
            .field("date_of_birth", &self.date_of_birth)
            .field("gender", &self.gender)
            .field("country_code", &self.country_code)
            .field("opt_in", &self.opt_in)
            .field("third_party_opt_in", &self.third_party_opt_in)
            .field("first_name", &self.first_name)
            .field("last_name", &self.last_name)
            .field("preferred_language", &self.preferred_language)
            .field("external_accounts", &self.external_accounts)
            .finish()
    }
}
#[derive(Debug, ToStream, FromStream)]
pub struct TOS {
    pub locale_code: String,
    pub content: String,
    pub storing_info_question: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct TOSEx {
    pub locale_code: String,
    pub contents: Vec<String>,
    pub storing_info_question: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct ValidationFailureReason {
    pub validation_id: u32,
    pub description: String,
}
#[derive(Debug, ToStream, FromStream)]
pub struct UsernameValidation {
    pub suggestions: Vec<String>,
    pub reasons: Vec<ValidationFailureReason>,
}
#[derive(Debug, ToStream, FromStream)]
pub struct Country {
    pub code: String,
    pub name: String,
}
