syntax = "proto3";

package misc;

import "users.proto";

service Misc {
    rpc Event(EventRequest) returns (EventResponse);
    rpc TestP2P(TestP2PRequest) returns (TestP2PResponse);
}

message EventRequest {}
message EventResponse {
    InviteEvent invite = 1;
    FriendEvent friend = 2;
}

message FriendEvent {
    enum Kind {
        // They asked the player to be friends.
        REQUEST = 0;
        // They accepted the player's request.
        ACCEPTED = 1;
    }
    Kind kind = 1;
    users.User from = 2;
}

message InviteEvent {
    int64 id = 1;
    users.User sender = 2;
    bool force_join = 3;
}

message TestP2PRequest {
    bytes challenge = 1;
}
message TestP2PResponse {
    bytes challenge = 2;
}