[package]
name = "coordinator"
version = "0.3.0"
edition = "2021"
description = "Shares friends between 5th Echelon servers, and lists them in a server directory"

[dependencies]
argh = { workspace = true }
argon2 = { workspace = true }
base64 = "0.22"
ciborium = "0.2"
geo = { path = "../geo" }
hmac = { workspace = true }
qrcode = { version = "0.14", default-features = false, features = ["svg"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
ring = "0.17"
sha1 = "0.10"
axum = { version = "0.8", default-features = false, features = ["http1", "json", "tokio", "query", "ws"] }
eyre = { workspace = true }
identity = { path = "../identity" }
stat_boards = { path = "../stat_boards" }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net", "signal", "sync", "time"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
